### PR TITLE
Add export as image options to Hide grid and change background color

### PR DESCRIPTION
**Pull request by vacharanon**
Hi.

I've tried to add 2 options when exporting as image.
- Hide grid
- Change background color

The UI is still rough and need help over there but I think this should be the idea.

### CODE REVIEW

**Comment by markmanx** [comment]
This is a good addition @vacharanon, thanks.  For design direction I would recommend the following.  Do you have the time to implement?

image

**Comment by vacharanon** [comment]
That's good thinking. 
I still have some free time and will try to get it together.

**Comment by vacharanon** [comment]
I've improved the UI as per suggestion. 
Additionally,
- Create a "ColorPicker" component to reuse button style from ColorSwatch.
- Refactor and utilize useEffect to redraw preview.

I never use a project with MUI and my React is very rusty. Please feel free to review.

**Comment by markmanx** [comment]
@vacharanon Nice work, thankyou.

**Pull request merged**
